# Generated by Django 4.2 on 2025-01-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Historical', 'Historical'), ('Futuristic', 'Futuristic'), ('Mythical', 'Mythical')], default='null', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_destinations.type')),
            ],
        ),
    ]
